version: '3'

services:
  prototype-db:
    image: mysql:latest
    container_name: prototype-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    volumes:
      - ./data:/var/lib/mysql
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    ports:
      - 3306:3306

  auth-prototype-api:
    build: .
    container_name: auth-prototype-api
    volumes:
      - .:/usr/app
    expose:
      - 3333
    ports:
      - 3333:3333
    environment:
      - LISTEN_PORT=3333
      - DB_PORT=3306
      - DB_HOST=prototype-db
      - DB_NAME=boca-ex
      - DB_USER=root
      - DB_PASSWORD=root
      - LDAP_BASE_DN=dc=inf,dc=ufes,dc=br
      - LDAP_SERVER=ldap://ldap:389
      - LDAP_USER=cn=admin,dc=inf,dc=ufes,dc=br
      - LDAP_ADMIN_PASSWORD=ldappw
    depends_on:
      - prototype-db
      - ldap

  ldap:
      image: osixia/openldap:1.3.0
      container_name: ldap
      volumes:
        - ./ldap:/container/service/slapd/assets/config/bootstrap/ldif/custom
      command: --copy-service
      environment: 
        LDAP_ORGANISATION: 'DI'
        LDAP_DOMAIN: 'inf.ufes.br'
        LDAP_BASE_DN: 'dc=inf,dc=ufes,dc=br'
        LDAP_ADMIN_PASSWORD: 'ldappw'
        TZ: America/Sao_Paulo
      ports:
        - 389:389
      expose:
        - 389

  lam:
      image: ldapaccountmanager/lam:stable
      container_name: lam
      ports:
        - 8081:80
      environment: 
        LDAP_DOMAIN: 'inf.ufes.br'
        LDAP_BASE_DN: 'dc=inf,dc=ufes,dc=br'
        LDAP_SERVER: 'ldap://ldap:389'
        LDAP_USER: 'cn=admin,dc=inf,dc=ufes,dc=br'
        LAM_PASSWORD: 'ldappw'
        LDAP_ADMIN_PASSWORD: 'ldappw'
        LDAP_ORGANISATION: 'DI'
        TZ: America/Sao_Paulo
      depends_on:
        - ldap
