version: '3'

services:
  prototype-db:
    image: postgres:latest
    container_name: prototype-db
    restart: always
    environment:
      POSTGRES_DB: boca_ex
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./pgscripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432

  auth-prototype-api:
    image: auth-prototype-api
    build: .
    volumes:
      - .:/usr/app
    expose:
      - 3333
    ports:
      - 3333:3333
    environment:
      - LISTEN_PORT=3333
      - DB_PORT=5432
      - DB_HOST=prototype-db
      - DB_NAME=boca_ex
      - DB_USER=root
      - DB_PASSWORD=root
      - LDAP_BASE_DN=dc=inf,dc=ufes,dc=br
      - LDAP_SERVER=ldap://ldap:389
      - LDAP_USER=cn=admin,dc=inf,dc=ufes,dc=br
      - LDAP_ADMIN_PASSWORD=ldappw
    depends_on:
      - prototype-db
      - ldap

  ldap:
    image: osixia/openldap:1.3.0
    container_name: ldap
    volumes:
      - ./ldap:/container/service/slapd/assets/config/bootstrap/ldif/custom
    command: --copy-service
    environment: 
      LDAP_ORGANISATION: 'DI'
      LDAP_DOMAIN: 'inf.ufes.br'
      LDAP_BASE_DN: 'dc=inf,dc=ufes,dc=br'
      LDAP_ADMIN_PASSWORD: 'ldappw'
      TZ: America/Sao_Paulo
    ports:
      - 389:389
    expose:
      - 389

  lam:
    image: ldapaccountmanager/lam:stable
    container_name: lam
    ports:
      - 8081:80
    environment: 
      LDAP_DOMAIN: 'inf.ufes.br'
      LDAP_BASE_DN: 'dc=inf,dc=ufes,dc=br'
      LDAP_SERVER: 'ldap://ldap:389'
      LDAP_USER: 'cn=admin,dc=inf,dc=ufes,dc=br'
      LAM_PASSWORD: 'ldappw'
      LDAP_ADMIN_PASSWORD: 'ldappw'
      LDAP_ORGANISATION: 'DI'
      TZ: America/Sao_Paulo
    depends_on:
      - ldap

volumes:
  pgdata: